const MODAL_WINDOW_VISIBILITY:string = 'MODAL_WINDOW_VISIBILITY';
const ADD_NOTE:string = 'ADD_NOTE';
const EDIT_NOTE:string = 'EDIT_NOTE';
const REMOVE_NOTE:string = 'REMOVE_NOTE';
const REMOVE_ALL_NOTES:string = 'REMOVE_ALL_NOTES';
const SET_MODAL_WINDOW_DATA:string = 'SET_MODAL_WINDOW_DATA';
const TOGGLE_SHOW_ARCHIVES:string = 'TOGGLE_SHOW_ARCHIVES';
const TOGGLE_ARCHIVE_STATE_NOTE:string = 'TOGGLE_ARCHIVE_STATE_NOTE';

export {
    MODAL_WINDOW_VISIBILITY,
    ADD_NOTE,
    EDIT_NOTE,
    REMOVE_NOTE,
    REMOVE_ALL_NOTES,
    SET_MODAL_WINDOW_DATA,
    TOGGLE_SHOW_ARCHIVES,
    TOGGLE_ARCHIVE_STATE_NOTE,
};
