const MODAL_WINDOW_VISIBILITY:string = 'MODAL_WINDOW_VISIBILITY';
const ADD_NOTE:string = 'ADD_NOTE';
const SET_MODAL_WINDOW_DATA:string = 'SET_MODAL_WINDOW_DATA';
const TOGGLE_SHOW_ARCHIVES:string = 'TOGGLE_SHOW_ARCHIVES';

export {
    MODAL_WINDOW_VISIBILITY,
    ADD_NOTE,
    SET_MODAL_WINDOW_DATA,
    TOGGLE_SHOW_ARCHIVES,
};
